01-create_window.out:
	gcc -g 01-create_window.c -o 01-create_window.out -lSDL2 

02-initializes_sdl.out:
	gcc -g 02-initializes_sdl.c -o 02-initializes_sdl.out -lSDL2

03-create_window.out:
	gcc -g 03-create_window.c -o 03-create_window.out -lSDL2 

04-load_image.out:
	gcc -g 04-load_image.c -o 04-load_image.out -lSDL2  -lSDL2_image

05-animation.out:
	gcc -g 05-animation.c -o 05-animation.out -lSDL2  -lSDL2_image

06-events.out:
	gcc -g 06-events.c -o 06-events.out -lSDL2  -lSDL2_image

07-keyboard.out:
	gcc -g 07-keyboard.c -o 07-keyboard.out -lSDL2  -lSDL2_image

08-mouse.out:
	gcc -g 08-mouse.c -o 08-mouse.out -lSDL2  -lSDL2_image -lm


clean:
	rm -rf *.out