target: createdata.out
createdata.out: 
	gcc -g3 -O0 create_data.c -o createdata.out

target: bubblesort.out
bubblesort.out: 
	gcc -g3 -O0 bubble_sort.c -o bubblesort.out

target: selectionsort.out
selectionsort.out: 
	gcc -g3 -O0 selection_sort.c -o selectionsort.out

clean:
	rm -rf *.out