SRC := 	02-buttons \
    	03-container_vbox \
    	04-container_hbox \
    	05-container_horizontal_pane \
    	06-container_vertical_pane \
    	07-container_tables \
    	08-container_fixed \
    	09-container_expanders \
    	10-handle_boxes \
    	11-container_notebook \
    	12-events_boxes \
    	13-toogle_buttons \
    	14-checkbuttons \
    	15-radiobuttons \
    	16-entries \
    	17-spinbuttons \
    	18-scales \
    	19-colorbuttons \
    	20-filechooserbuttons \
    	21-fontbuttons \
    	22-dialogs \
     	23-form_dialog 

